# .goreleaser.yml
project_name: delator
# Build customization
builds:
  - binary: delator
    goos:
      - windows
    goarch:
      - amd64
      - 386
# Archive customization
archives:
- replacements:
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip