# .goreleaser.yml
project_name: delator
# Build customization
builds:
  - binary: delator
    goos:
      - windows
    goarch:
      - amd64
      - 386
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    386: 32-bit
  format_overrides:
    - goos: windows
      format: zip